name: Publish GA

on:
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch: 
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/npm_publish:latest
    steps:  
    - uses: actions/checkout@v3
    - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PASS }}
    - run: npm install .
    - run: npm publish .
